language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

notifications:
    slack: simone-app:ZuDGmNIMJSK28PW3c8Elca5G

before_script:
    - chmod +x ./gradlew      #Grand permissions
    - android list targets
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - android-wait-for-emulator
    - adb devices   #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedCheck -PdisablePreDex --stacktrace

before_install:
    - pip install --user codecov    #Install codecov

after_success:
    - codecov                       #Run codecov