language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  matrix:
    - API=android-15 ABI=armeabi-v7a
    - API=android-16 ABI=armeabi-v7a
    - API=android-17 ABI=armeabi-v7a
    - API=android-18 ABI=armeabi-v7a
    - API=android-19 ABI=armeabi-v7a
    - API=android-21 ABI=armeabi-v7a
    - API=android-22 ABI=armeabi-v7a
    - API=android-24 ABI=armeabi-v7a
    - API=android-24 ABI=arm64-v8a

# Emulator Management: Create, Start and Wait
before_script:
  - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t $API --abi $ABI
  - emulator -avd test -no-audio -no-window
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - chmod +x ./gradlew
  - ./gradlew clean assemble
  
notifications:
    slack: simone-app:ZuDGmNIMJSK28PW3c8Elca5G
